export const FONTS = [
  { label: 'Default font', value: '' },
  { label: 'Siyuan black body', value: 'SourceHanSans' },
  { label: 'Siyuan Songti', value: 'SourceHanSerif' },
  { label: 'Founder black body', value: 'FangZhengHeiTi' },
  { label: 'Founder regular script', value: 'FangZhengKaiTi' },
  { label: 'Founder Song style', value: 'FangZhengShuSong' },
  { label: 'Founder imitates Song Dynasty', value: 'FangZhengFangSong' },
  { label: 'Alibaba inclusive body', value: 'AlibabaPuHuiTi' },
  { label: 'Zhuque imitates Song Dynasty', value: 'ZhuqueFangSong' },
  { label: 'Xiayu Wenkai', value: 'LXGWWenKai' },
  { label: 'WendingPLregular script', value: 'WenDingPLKaiTi' },
  { label: 'proudly black', value: 'DeYiHei' },
  { label: 'MiSans', value: 'MiSans' },
  { label: 'Cang Er small balls', value: 'CangerXiaowanzi' },
  { label: 'Excellent title black', value: 'YousheTitleBlack' },
  { label: 'Feng Guang Ming Rui Body', value: 'FengguangMingrui' },
  { label: 'Photography of modern small cube', value: 'ShetuModernSquare' },
  { label: 'Station cool happy body', value: 'ZcoolHappy' },
  { label: 'Ximai style in Zhizhi District', value: 'ZizhiQuXiMai' },
  { label: 'Material bazaar kangkangti', value: 'SucaiJishiKangkang' },
  { label: 'Material Market Coolcube', value: 'SucaiJishiCoolSquare' },
  { label: 'Tuniu-like round body', value: 'TuniuRounded' },
  { label: 'Ruizhenyan style', value: 'RuiziZhenyan' },
]